export const CREATE = "CREATE_POST"
export const UPDATE = "UPDATE_POST"
export const LIKE = "LIKE_POST"
export const DELETE = "DELETE_POST"
export const FETCH = "FETCH_ALL"
export const FETCH_SEARCH = "FETCH_SEARCH"
export const AUTH = "AUTH"
export const LOGOUT = "LOGOUT"
